### ISSUE TITLE
Video call is not closing when provider hangs up

### ISSUE THREAD

**Issue by danielmurcia** [CirrusMD/CirrusMD-Android-SDK-Example#40] opened 2021-05-27 21:31 UTC
Hello there,

We've been working recently with your SDK and just found that when in a video call, as the provider hangs up, the video Activity background turns to white and it doesn't close, until the user taps the back button.

![cirrus white screen](https://user-images.githubusercontent.com/4340905/119899604-f1110480-bf08-11eb-925c-1378bdc24ff0.png)

Is this expected?

**Comment by taylorjcase** [comment] 2021-05-28 19:04
This is expected behavior. Previously we did not have a way of resolving this due to a third party dependency. However, there is a new version of that dependency available that may help us resolve this in a future release.

**Comment by DanielGalarza** [comment] 2022-05-23 21:55
@danielmurcia This issue has been resolved in v9.5.0!

**Closed as completed by DanielGalarza** 2022-05-23 21:55 UTC
